language: node_js
node_js:
  - "6"
  - "6.1"
addons:
  code_climate:
    repo_token: 94fa8427cfb5888f792087317924a41e095a6744f5e3f61e14327d4bd0a9b1fe
sudo: false
before_script:
  - yarn
  - yarn global add gulp
after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
cache:
  yarn: true